### ISSUE TITLE
Envoyer les logs d'accès dans ElasticSearch 

### ISSUE THREAD

**Issue by brindu** [etalab/sirene_as_api#108]
Rajouter un pipe logstash couplé avec logstasher (gem ruby) pour envoyer les logs d'accès à entreprise.data.gouv.fr dans ElasticSearch.

**Comment by giglemad** [comment]
favorable a ce que ça reste sur la même machine, bien séparé du reste de notre infra

**Comment by brindu** [comment]
@giglemad je suis pas certain d'avoir saisi ce que tu entends exactement avec ce commentaire ^^'

**Comment by Samuelfaure** [comment]
done in https://github.com/etalab/sirene_as_api/pull/125/commits/3383526b0d08c19b688bd3589e493a5e9587d2eb
