### ISSUE TITLE
Filter by Creation Date

### ISSUE THREAD

**Issue by bricemaurin** [etalab/sirene_as_api#159]
I'm trying to filter results by company creation date, but the filter doesn't seem to be available. Am I wrong ?

Thanks !

**Comment by Samuelfaure** [comment]
This option is indeed not available at the moment. The team is a bit busy at the moment but I should personally be back to work in about a month, you can expect this feature to be implemented by then.

Thanks for your issue !

**Comment by bricemaurin** [comment]
So fast ! Thanks Samuel, that'd be amazing :)

**Comment by Haelle** [comment]
the /v3 version allow now to search on all fields, and many of them are indexed now
