### ISSUE TITLE
Evolutions INSEE 3.6

### ISSUE THREAD

**Issue by hugolepetit** [etalab/sirene_as_api#161]
Bonjour,

Nous vous informons que l'API Sirene va passer en version 3.6 pour préparer l'ouverture fin mars :
- du service « Liens de succession » qui permet d'accéder aux siret des prédécesseurs et des successeurs,
- de la possibilité de passer des requêtes POST dans les services multicritères siren et siret pour permettre des requêtes de longueur plus importante.
Cette montée contient également la correction de deux bugs signalés par des utilisateurs :
- le libellé de voie qui dans quelques cas pouvait à tort être à null,
- l'indicateur de changement parfois à true alors qu'il n'y avait qu'une seule période.

Pour toute question, vous pouvez nous contacter via le formulaire de contact du catalogue des API de l'Insee : https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/help.jag#contact

Pour vous abonner à notre lettre d'information Sirene open data actualités, suivez ce lien : https://insee.fr/fr/information/1405555 

Cordialement,

L'équipe Sirene Diffusion

**Comment by brindu** [comment]
@giglemad Qu'est-ce que tu voulais qu'on fasse de ce mail concernant les évolutions des API ? C'était censé engranger quoi comme changement ?
