### ISSUE TITLE
Filtre par date d'immatriculation

### ISSUE THREAD

**Issue by alexsonnay** [etalab/sirene_as_api#164]
Est-il en développement ou dans les features à venir ?

**Comment by Samuelfaure** [comment]
Le projet a avancé doucement car je ne travaille plus depuis fin décembre, mais je reprend aujourd'hui !
Cette feature n'est pas une priorité pour le moment mais ne devrait pas prendre trop de temps, je pense pouvoir la caler dans la roadmap des trois prochains mois.

**Comment by Haelle** [comment]
La v3 est maintenant disponible est permet de filtrer sur tous les champs, nombre d'entre eux sont indexés
