### ISSUE TITLE
Migration de l'import en utilisant le nouveau format de fichier de l'INSEE

### ISSUE THREAD

**Issue by brindu** [etalab/sirene_as_api#167]
Le format des fichiers mis à disposition par l'INSEE sur data.gouv a changé au 31 avril 2019. Aujourd'hui on reconstitue la base SIRENE à partir d'un reformatage (et d'un géocodage) des nouveaux fichiers vers les anciens réalisé quotidiennement par Christian Quest. 

Mise à niveau nécessaire pour reconstituer la base SIRENE à partir du nouveau format de fichier (ceux géocodés par Christian, bien entendu).

**Comment by Samuelfaure** [comment]
Pour info voici la liste des headers d'import, par mesure de simplicité je propose de les garder (ils sont bien plus lisibles qu'en V2), après conversion en snake_case evidemment.

siren
nic
siret
statutDiffusionEtablissement
dateCreationEtablissement
trancheEffectifsEtablissement
anneeEffectifsEtablissement
activitePrincipaleRegistreMetiersEtablissement
dateDernierTraitementEtablissement
etablissementSiege
nombrePeriodesEtablissement
complementAdresseEtablissement
numeroVoieEtablissement
indiceRepetitionEtablissement
typeVoieEtablissement
libelleVoieEtablissement
codePostalEtablissement
libelleCommuneEtablissement
libelleCommuneEtrangerEtablissement
distributionSpecialeEtablissement
codeCommuneEtablissement
codeCedexEtablissement
libelleCedexEtablissement
codePaysEtrangerEtablissement
libellePaysEtrangerEtablissement
complementAdresse2Etablissement
numeroVoie2Etablissement
indiceRepetition2Etablissement
typeVoie2Etablissement
libelleVoie2Etablissement
codePostal2Etablissement
libelleCommune2Etablissement
libelleCommuneEtranger2Etablissement
distributionSpeciale2Etablissement
codeCommune2Etablissement
codeCedex2Etablissement
libelleCedex2Etablissement
codePaysEtranger2Etablissement
libellePaysEtranger2Etablissement
dateDebut
etatAdministratifEtablissement
enseigne1Etablissement
enseigne2Etablissement
enseigne3Etablissement
denominationUsuelleEtablissement
activitePrincipaleEtablissement
nomenclatureActivitePrincipaleEtablissement
caractereEmployeurEtablissement
longitude
latitude
geo_score
geo_type
geo_adresse
geo_id
geo_ligne
geo_l4
geo_l5

**Comment by brindu** [comment]
Je suis même pour une suppression des suffixes "Etablissement" qui n'apportent aucune précision car répétés partout, d'autant plus si tous ces attributs appartiennent à un modèle *Etablissement".
