### ISSUE TITLE
Send newsletter Dockerize

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/sirene_as_api#173]
cf #172

**Comment by Samuelfaure** [comment]
Might also be worth warning people that our API v2 will be marked as deprecated soon ?....

**Comment by brindu** [comment]
Oui, il faut cependant faire valider cette com' externe et la durée pendant laquelle on maintient la V2 actuelle. Je dirai qu'il faut voir avec Romain maintenant.

**Comment by Samuelfaure** [comment]
Assignating @brindu , dont forget to close the issue when you send the newsletter
