### ISSUE TITLE
Extraire documentation du README

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/sirene_as_api#187]
Le README est beaucoup trop gros, il devient necessaire de centraliser la doc ailleurs

(Possiblement a croiser avec les autres APIs)

**Comment by brindu** [comment]
Oui je pense que ça rentre dans le cadre du sujet de documentation pour entreprise.data et API Entreprise. 

https://github.com/etalab/entreprise.data.gouv.fr/issues/292
https://github.com/etalab/doc.entreprise.api.gouv.fr/issues/18
