### ISSUE TITLE
Description des variables

### ISSUE THREAD

**Issue by sebvita** [etalab/sirene_as_api#192]
Bonjour,

Existe-t-il une description des différentes variables retournées par l'API ? Et éventuellement la source de données permettant de les "traduire" ?
Par exemple, le SIRET d'un micro-entrepreneur (donc entreprise individuelle) retourne une variable `nature_entrepreneur_individuel` = 5 : à quoi cela correspond ? Y a-t-il une liste exhaustive ?
Pour une SARL, la `nature_juridique_entreprise` retourne un entier que l'on peut retrouver dans les formes juridique d'info greffe (https://opendata.datainfogreffe.fr/explore/dataset/forme-juridique/table/?sort=libelle), mais n'est pas une clé unique permettant de récupérer le libellé ; existe-t-il une autre variable ?

Merci par avance.

**Comment by Samuelfaure** [comment]
Bonjour,

Les variables des fichiers V2 (disponibilité stoppée en mars) sont documentées sur le site de l'INSEE.

Les fichiers actuels étant V3, vous pouvez trouver la doc complète sur Data.gouv : https://www.data.gouv.fr/en/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/

Notez que l'API importe pour le moment seulement les fichiers V2, notre chantier actuel est le passage à la V3.
