### ISSUE TITLE
erreur de mise à jour sur le téléchargement 2019-07/geo_sirene.csv.gz

### ISSUE THREAD

**Issue by epa64** [etalab/sirene_as_api#195]
Bonjour à tous,
Je maintiens un serveur siren_as_api qui tourne depuis 4 mois.
Lors la dernière mise à jour automatique la base c'est vidée et j'ai ce message explicite : 
Visiting monthly stock distant directory
       ^[  Retrieved last monthly stock link name : http://data.cquest.org/geo_sirene/2019-07/geo_sirene.csv.gz^[[0m
       ^[[Error : http://data.cquest.org/geo_sirene/2019-07/geo_sirene.csv.gz could not be reached
Si j'ai bien compris le format a changé, plus qu'un fichier geo mais 2 fichiers Etablissement.
Existe t'il une mise à jours dans le code d'etalab ?
Si non quelle autre solution.
Merci d'avance
Eric Papet

**Comment by Samuelfaure** [comment]
Bonjour,

En effet, les fichiers importés ne sont plus mis en ligne. Le dernier date de mars.
Je merge aujourdhui sur master : les dernieres modifications + un correctif pour telecharger correctement le dernier fichier de mars.

Inscrivez vous si vous le désirez à la mailing list sur entreprise.data.gouv.fr pour les avancées sur la nouvelle version qui permettra d'obtenir les données à jour.

**Comment by Samuelfaure** [comment]
fixed in #197
