### ISSUE TITLE
Bad download link

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/sirene_as_api#209]
Bonjour,

Je viens de remarquer que Sirene voit bien le fichier d'Aout 2019 comme étant le dernier en date, mais il telecharge le fichier de Juillet 2019, et il y a une erreur dans le fichier, d'après le retour de la console
![Screenshot 2019-08-26 at 13 42 02](https://user-images.githubusercontent.com/49921482/63688328-5e10db00-c807-11e9-96c0-348e4c29740c.png)

Autre chose que je viens de remarquer également. La version de SmarterCSV fait planter le peuplement de la base
![Screenshot 2019-08-27 at 10 04 24](https://user-images.githubusercontent.com/49921482/63752793-257a0b80-c8b2-11e9-838e-952b6f0d5f37.png)

**Comment by Samuelfaure** [comment]
Bonjour

Vu notre migration actuelle, certains problèmes peuvent apparaître. Je vais regarder cela de plus près au plus vite.

Assurez vous de bien utiliser la branche Master.

**Comment by Samuelfaure** [comment]
(EDIT: Précision importante, la branche Master n'était pas à jour, c'est maintenant chose faite)
