### ISSUE TITLE
Peuplement de la base impossible

### ISSUE THREAD

**Issue by jgauby** [etalab/sirene_as_api#210]
Bonjour,

Je cherche à monter un serveur, j'ai utilisé https://github.com/etalab/sirene_as_api_ansible, tout s'est plutôt bien passé : j'ai dû faire quelques ajustements à la conf de nginx, ajouter l'user deploy à la main notamment.

Mais désormais je me heurte à un bug lors du peuplement de la base avec `bundle exec rake sirene_as_api:populate_database RAILS_ENV=production` :

```
PG::UndefinedColumn: ERROR:  column "l1_normalisee" of relation "etablissements" does not exist
LINE 1: ...lissements (created_at,updated_at,siren,siret,nic,l1_normali...
                                                             ^
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/var/www/sirene_production/releases/10/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/var/www/sirene_production/releases/10/app/jobs/insert_etablissement_rows_job.rb:26:in `insert'
```

La classe `EtablissementAttrsFromLine` ne semble pas à jour : il y a présence de `l1_normalisee` alors que cette colonne a disparu dans le modèle `Etablissement`.
 
C'est lié au passage de la v3 je pense. Une idée pour fixer ? Une idée de date de livraison d'une version fonctionnelle de la v3 ?

**Comment by Samuelfaure** [comment]
Bonjour
Il semble y avoir eu des erreurs dans le merge la semaine dernière. Je regarde ça au plus vite.

**Comment by Samuelfaure** [comment]
Rebonjour,

Après investigation : la V3 semble bien fonctionnelle en sandbox et production. L'import se lance automatiquement avec les tâches CRON (cf le fichier `config/schedule.yml`.

Attention il faudra avoir `redis` d'installé sur le serveur. Le ansible n'est pas à jour (et ne sera pas mis à jour avant un certain temps).

La V2 a un problème de fichier corrompu, j'averti notre fournisseur de donnée qui fait le nécessaire.

**Comment by jgauby** [comment]
Rebonjour. Je me suis donc placé sur la branche `insee_v3`. Et en effet après avoir installé `redis`, configurer `redis_database` dans config/environments/production.rb, l'import se déroule bien. Merci pour le support !
