### ISSUE TITLE
Mina deploy erreur

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/sirene_as_api#213]
Bonjour,

Lors du déploiement par Mina, je tombe sur une erreur `NoMethodError: undefined method redis_database for #<Rails::Application::Configuration:0x000055e78a7c2910>`

Bug ? 

Cordialement

**Comment by Samuelfaure** [comment]
Bonjour,

La configuration de redis se fait dans le fichier /config/environments/development.rb
Pour la production, vous devez avoir un fichier production.rb au même endroit

Redis doit être installé sur la machine hôte et une ligne dans `production.rb` doit comporter la ligne `config.redis_database = "<adresse de votre serveur redis>"`

A priori cela devrait régler le soucis. Nous mettrons la documentation à jour ASAP
