### ISSUE TITLE
Optimisation requêtes / indexations supplémentaires

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/sirene_as_api#214]
Les requêtes pour certains siren (la poste...) sont beaucoup trop longues.
=> Trouver un moyen d'optimiser
=> Rajouter autant d'indexs que nécessaire

**Comment by kofronpi** [comment]
@Samuelfaure  si je peux me permettre, sur l'endpoint v3 un index par code postal, code naf et établissement actif serait très utile pour récupérer tous les établissements actifs d'une commune : 

`add_index :etablissements_v2, [:code_postal, :activite_principale, :etat_administratif]`

Actuellement les requêtes de ce type time-out, même avec un timeout à 30s.

Je ne peux pas faire de PR - pas le temps d'installer votre environnement de de développement.

**Comment by kofronpi** [comment]
@Samuelfaure en fait plutôt par code INSEE que code postal ;)

`add_index :etablissements_v2, [:code_insee, :activite_principale, :etat_administratif]`

**Comment by Samuelfaure** [comment]
J'ai entamé une PR là dessus : #228 

Verifiez si vous n'avez pas besoin d'index supplémentaires que ceux qui seront rajoutés :)
