### ISSUE TITLE
Erreur Sidekiq

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/sirene_as_api#215]
Bonjour, je reviens encore une fois vers vous pour vous rapporter une erreur que j'ai remarqué lors du déploiement de Mina.
La solution d'installer redis sur le serveur et d'ajouter l'adresse au fichier production.rb.j2 fonctionne très bien.
Malheureusement je me retrouver avec une nouvelle erreur lors du déploiement de Mina.

![Screenshot 2019-09-09 at 12 12 39](https://user-images.githubusercontent.com/49921482/64522798-2328a000-d2fb-11e9-8311-36ef1a8c07e7.png)

Cela empeche le dossier "current" de se remplir et donc de peupler la base.

Merci de votre aide

Cordialement

**Comment by Samuelfaure** [comment]
Bonjour,

Il est nécessaire de créer un service `sidekiq` pour l'application. Si le serveur de production est un debian ou ubuntu, le gestionnaire de service est probablement systemd.

Un exemple de fichier permettant de créer ce service systemd est disponible ici : https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service

Cordialement
