### ISSUE TITLE
champ nature_entrepeneur_individuel=null pour toutes les requetes

### ISSUE THREAD

**Issue by eauc** [etalab/sirene_as_api#216]
Bonjour,

désolé de poster ca ici mais j'ai pas trouvé des masses de contact pour ce genre de question.

Depuis quelques jours tous les documents retournés par des requetes à `https://entreprise.data.gouv.fr/api/sirene/v1/` semblent avoir leur champ `nature_entrepreneur_individuel` = null ?

Une raison particulière ?

Merci d'avance

**Comment by Samuelfaure** [comment]
Bonjour,

L'API /v1/ et /v2/ utilise les anciens formats de fichier de l'INSEE, qui ne sont plus délivrés depuis le début de l'année.
Les fichiers ont changé depuis : nous faisons une conversion depuis le nouveau format vers l'ancien, mais certains champs ne sont plus renseignés du tout par l'INSEE.

Depuis peu nous avons mis en ligne de nouveaux endpoints qui retournent les derniers fichiers avec leur format V3 : `https://entreprise.data.gouv.fr/api/sirene/v3/unites_legales/SIREN` et `/v3/etablissements/SIRET`, vous pouvez regarder sur ces endpoints si l'information s'y trouve. Attention ils sont encore en beta.

**Comment by eauc** [comment]
Ok merci beaucoup pour cette reponse rapide :+1:
