### ISSUE TITLE
Rake aborted on attempting to download etablissements[...]

### ISSUE THREAD

**Issue by QuentinSu** [etalab/sirene_as_api#218]
Hi,

I'm trying to deploy with docker sirene_as_api but i'm stucking when i try to run 
`docker-compose run sirene rake sirene_as_api:populate_database`

After few minutes on "Attempting to download etablissements_actifs_2019_08.csv.gz", i get this : 

`rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ./tmp/files/etablissements_actifs_2019_08.csv.gz
/docker_build/app/interactors/download_file.rb:22:in `initialize'
/docker_build/app/interactors/download_file.rb:22:in `copy_stream'
/docker_build/app/interactors/download_file.rb:22:in `call'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:213:in `block in with_hooks'
/docker_build/app/interactors/download_file.rb:12:in `block in <class:DownloadFile>'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:263:in `instance_exec'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:263:in `run_hook'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:76:in `tap'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:76:in `call!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:79:in `block in call'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:78:in `each'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:78:in `call'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:213:in `block in with_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:76:in `tap'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:76:in `call!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:79:in `block in call'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:78:in `each'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/organizer.rb:78:in `call'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:143:in `block in run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:213:in `block in with_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:224:in `run_around_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor/hooks.rb:211:in `with_hooks'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:142:in `run!'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:115:in `run'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:50:in `tap'
/usr/local/bundle/gems/interactor-3.1.0/lib/interactor.rb:50:in `call'
/docker_build/lib/tasks/sirene_as_api.rake:24:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => sirene_as_api:populate_database
(See full trace by running task with --trace)`

A docker-compose up succeed but the API returns no results (in full_text mode or siren)

Do you have an idea to solve this ?

Many thanks,

### EDIT
docker-compose up returns (in part):
psql:/docker-entrypoint-initdb.d/init.sql:0: could not read from input file: Is a directory

**Comment by QuentinSu** [comment]
EDIT : docker-compose up returns
psql:/docker-entrypoint-initdb.d/init.sql:0: could not read from input file: Is a directory
I don't really know why

**Comment by Samuelfaure** [comment]
Hello,

Thanks for this issue, we will look into it when we have time. In the meantime you can try a manual 
 install or use the API in production at `https://entreprise.data.gouv.fr/api/sirene/v1...`. We recently increased the request limit up to **7 request a second** (more than this will return a code 429, your IP should not get banned.)

**Comment by mlahitte** [comment]
Bonjour, c'est peut être un peu tard pour vous mais l'info peut bénéficier à d'autres.
Pour résoudre le problème évoquer dans la partie Edit il faut modifier le fichier docker-compose.yml.
https://github.com/etalab/sirene_as_api/issues/221#issuecomment-584223067
