### ISSUE TITLE
Informations manquantes dans le retour de l'API entreprise SIREN

### ISSUE THREAD

**Issue by pierredittgen** [etalab/sirene_as_api#220]
Bonjour,

J'utilise depuis peu l'API de recherche par SIREN (https://entreprise.data.gouv.fr/api/sirene/v1/siren/) pour récupérer un certain nombre d'informations sur une liste de collectivités locales dont j'ai le siren.

Je trouve l'API très rapide et j'apprécie la richesse des informations renvoyées. Je récupère en particulier : le nom (`l1_normalisee`), les coordonnées GPS (`latitude`, `longitude`) le code région, le libellé région et le code département. 

La plupart des recherches me renvoie toutes ces informations mais dans certains cas, j'ai constaté des manques :

1) La recherche sur 200013704 ou 200013746 me renvoie seulement le nom des communes (respectivement "COMMUNE DE MAHINA" et "COMMUNE DE PIRAE")

2) La recherche sur 200046977 (METROPOLE DE LYON) renvoie le code région mais pas le libellé. C'est le cas également pour 211300553 (COMMUNE DE MARSEILLE) et 217500016 (VILLE DE PARIS)

3) La recherche sur 210600656 (COMMUNE DE LA GAUDE) ne renvoie pas de coordonnées GPS. C'est le cas également pour 212001630 (COMMUNE DE MONACIA D AULLENE)

Questions :
- Les informations non renvoyées par l'API sont elles déjà manquantes dans la base de données SIREN des entreprises ?
- Pour le libellé région, avez-vous envisagé de remplir les libellés manquants en faisant une jointure avec la table COG de l'INSEE ?
- Pensez-vous ajouter le libellé des départements dans la réponse ?

Merci d'avance pour vos réponses

Pierre Dittgen

**Comment by Samuelfaure** [comment]
Bonjour,

1/ Oui ! Nous renvoyons toutes les infos de la base SIREN sur l'API.
Attention, les informations des endpoints v1 et v2 sont "converties" depuis le nouveau format des fichiers SIRENE de l'INSEE. Le nouveau format est disponible sur les endpoints V3.

La documentation V3 est en cours de validation, une preview est disponible ici : https://sandbox.entreprise.data.gouv.fr/api_doc_sirene

Nous ajoutons les infos de géolocalisation, quand possible, grâce au travail bénévole d'enthousiastes du libre.

2/ et 3/, L'ajout des libéllés est une feature que nous envisageons, néanmoins le développement de l'API open data est pour le moment en pause de notre coté, donc pas de calendrier à donner sur de nouvelles features, toutefois si des développeurs souhaitent apporter leur pierre à ce projet open source, nous accueillerons les contributions avec plaisir.

**Comment by johanricher** [comment]
Bonjour,

Merci pour ces réponses très rapides !

Nous allons pour l'instant continuer à  utiliser le endpoint v1 puisque nous avons besoin des valeurs pour les attributs `departement`, `region` et `libelle_region` qui ne sont pas encore dans la v3. Pouvez-vous dire jusqu'à quelle date seront maintenus les v1 et v2 ?

Sachant que ces attributs ne sont pas non plus renvoyés par l'API de la BAN (adresse.data.gouv), pouvez-vous nous dire quelle était votre chaîne pour récupérer ces informations et les mettre dans les endpoints v1 et v2 ?

> Nous ajoutons les infos de géolocalisation, quand possible, grâce au travail bénévole d'enthousiastes du libre.

Si je comprends bien, l'API Sirene (entreprise.data.gouv) utilise la BAN pour géocoder les adresses de la base SIRENE. La BAN utilisant elle-même OpenStreetMap comme une des sources, si l'adresse n'y est pas, pas de géocodage possible. C'est bien ça ?

Auquel cas, pouvez-vous me dire combien de temps il se passe au minimum entre une contribution dans la base OSM et l'ajout dans la BAN ? et ensuite pour que l'adresse correspondante dans la base SIREN soit géocodée dans l'API Sirene entreprise.data.gouv ?

**Comment by Samuelfaure** [comment]
Bonjour,

Les attributs manquants étaient donnés dans les fichiers SIRENE ancienne version. Ces fichiers n'existent plus. Nous faisons une conversion des fichiers nouveau format vers ancien format pour assurer la continuité du service. Le script de conversion est disponible ici : https://github.com/cquest/retrosirene

Vu que les fichiers ne délivrent plus cette information, elle est probablement ajoutée au moment du geocodage. Les scripts de geocodage utilisés sont disponibles ici : https://github.com/cquest/geocodage-spd 

En effet le README mentionne l'utilisation de la BAN.

Le géocodage est fait au début de chaque mois pour les nouveaux fichiers stocks. La donnée est donc de fraîcheur mensuelle. Si la BAN est à jour au moment du géocodage, l'API devrait logiquement contenir les localisations à jour.

Concernant le délai pour mise à jour de données vers la BAN, nous n'avons pas cette information, je vous invite à contacter directement la BAN.

**Comment by johanricher** [comment]
Entendu, merci pour ces compléments d'information !
