### ISSUE TITLE
Docker deployment doesn't work anymore

### ISSUE THREAD

**Issue by julien1619** [etalab/sirene_as_api#221]
I'm trying to deploy sirene_as_api with Docker but I've encountered a few problems while doing it.

- Solr needs openjdk. The Dockerfile tries to install it while creating the container, but `openjdk-8-jre` has been removed from Debian Buster, which is the base image of the ruby image. Replacing it with `openjdk-11-jre` seems to make it work.
- The `Gemfile.lock` has been generated by the version 2.0.1, but the version in the Docker image is 1.17.3 so it fails to install Ruby dependencies. I've added `RUN gem install bundler --version 2.0.1 --force` to make it work.
- Some binaries are not executable, I need to add `RUN chmod u+x $APP_HOME/bin/*`.

Moreover, the instructions are not update for v3.

I don't know if this is normal and I missed something (a branch WIP or something), or if this method of deployment is not maintained. I can create a PR if needed ;)

PS : Mon ticket est en anglais mais n'hésitez pas à continuer en français.

**Comment by Samuelfaure** [comment]
Bonjour et merci pour l'issue.

Nous ne maintenons pas activement la "version docker" du repo car nous avons une architecture différente. Je n'ai donc pas de calendrier à donner pour la correction de ces problèmes.
Si vous avez le temps, je serais ravi de review une éventuelle PR.

**Comment by julien1619** [comment]
Bonjour,

Ok c'est noté. Je vais donc faire une PR avec les modifications que j'ai du effectuer pour que ça fonctionne.

**Comment by julien1619** [comment]
Je n'ai pas réussi à aboutir à quelquechose de fonctionnel, l'import de la v3 échouait à chaque fois. Je pense que les deux problèmes ne sont pas forcément liés, j'ai vu le ticket #236 qui a sans doute un lien avec ça.

Je ferai une PR malgré tout qui corrigera ce que j'ai pu corriger sur Docker mais sans certitude que ça fasse tout marcher.

Dans l'intervalle j'ai refait un service en Rust qui m'a permis d'utiliser les données de l'INSEE malgré tout. Si vous avez envie d'y jeter un oeil : https://github.com/Creatiwity/siren

**Comment by mlahitte** [comment]
Bonjour,
Merci pour cette api.
Pour faire fonctionner le container j'ai du modifié un peu les fichiers de configs.

Open-jdk 8 est nécessaire, il n'apparait pas dans les paquets debian buster, il suffit de l'installer manuellement depuis le bash du container ou via le fichier Dockerfile en téléchargeant les paquets necessaires (cf les dépendances). 
Attention tout ajout de commande RUN dans Dockerfile augmentera la taille des layers.
Par défaut c'est la version 11 de jdk qui sera utilisée, pour passer à la 8 il faut  utiliser update-alternative dans le container (en manuel ou via le fichier entrypoint):

`# update-alternatives --set java  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`

Il ya une erreur dans le fichier docker-compose.yml, le chemin de l'entrypoint n'est pas le bon pour le volume de la db, il manque le dossier docker entre config et init.sql
- ${HOST_APP_FOLDER}/config/docker/init.sql:/docker-entrypoint-initdb.d/init.sql

Avec ces changements la base est bien peuplée, solr fonctionne et génére convenablement le dictionnaire.

PS: Je ne trouve pas de fichier de configuration pour passer en production par contre.(ni dokcer, ni ansible)
