### ISSUE TITLE
Sortie de la v3 officielle ?

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/sirene_as_api#225]
Bonjour,
Je voulais vous demander si vous aviez une idée de la date de la sortie de la v3 officielle ?

Et si non, avez vous eu le temps de modifier la documentation afin d'ajouter la configuration du fichier sidekiq à créer pour l'application ?

Merci d'avance

Cordialement

**Comment by Samuelfaure** [comment]
Bonjour,

Une proposition de documentation à jour est disponible ici : https://github.com/etalab/sirene_as_api/tree/update_readme_v3

Notre calendrier de développement sur des projets annexes étant assez plein, nous n'avons pas encore de date pour la sortie officielle de la V3.
