### ISSUE TITLE
Problèmes import V3 automatique

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/sirene_as_api#229]
Suite à investigation sur server Sirene1 : Nous avons un stock UniteLegale à jour mais Etablissement refuse de se mettre à jour. Résultat des investigations :

- UpdateDatabaseJob appelle en Nested le chargement du stock UniteLegale (Stock::Operation::LoadUniteLegale) puis ensuite du stock Etablissement.
Actuellement, le stock UniteLegale a bien été importé, mais Etablissement est en erreur (suite à #222 )
=> Trailblazer retourne false (echec de l'import) au Nested UniteLegale car le stock n'est pas importable (il a été importé donc pas de raison de réimporter). 

Conséquences : si UniteLegale passe la première fois mais pas Etablissement, Etablissement ne sera jamais réimporté par la suite, car UniteLegale sera toujours un échec (ou du moins jusqu'au mois suivant, quand UniteLegale sera importé à nouveau).

Correctif : passer de `step` à `success` pour que les deux opérations soit lancées en parallèle dans tout les cas.

- Fichier PreLoadCheck en trop probablement suite à erreur de manipulation GIT + les specs, à supprimer.
=> A supprimer

- Pas de check si STOCK=PENDING ou LOADING avant d'importer, à priori (cf model/Stock.rb). On check bien pour ERROR ou COMPLETED.
=> A rajouter

- Pas de check au niveau du server pour vérifier si la machine est en frontal avant import
=> Probablement rajouter une classe pour wrapper UpdateDatabaseJob après un check de l'IP (check déjà codé pour la V1/V2)

**Comment by Haelle** [comment]
Normalement les imports tournent en parallèle ils ne s'attendent pas pour se lancer.

Par contre il y a en effet probablement un soucis si l'un réussit et que l'autre échoue ; alors relancer la tâche va probablement échouer.
C'est un comportement à corriger en effet.

Il faut en effet ajouter le check si la machine est en frontal !

**Comment by Samuelfaure** [comment]
Rectification point 3 : le code check bien si PENDING ou LOADING mais c'est dur à voir, je rajoute un commentaire pour l'éclaircir.
