### ISSUE TITLE
Erreur Solr Not found

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/sirene_as_api#231]
Bonjour,

J'ai tenter de déployer l'API Sirene sur mon serveur, le deploiement par Mina s'est bien passé (après quelques modifications de sidekiq), le peuplement se passe bien. Mais une fois à la reindexation je me retrouve avec l'erreur suivante :

rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 404 Not Found
Error:     Not Found

URI: http://localhost:8983/solr/production/update?wt=json
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:EtablissementV2</query></delete>"

Backtrace: /var/www/sirene_api_production/releases/1/vendor/bundle/ruby/2.4.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:196:in `rescue in execute'
/var/www/sirene_api_production/releases/1/vendor/bundle/ruby/2.4.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:186:in `execute'
...

Caused by:
Faraday::ResourceNotFound: the server responded with status 404
/var/www/sirene_api_production/releases/1/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.0/lib/faraday/response/raise_error.rb:8:in `on_complete'
/var/www/sirene_api_production/releases/1/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.0/lib/faraday/response.rb:9:in `block in call'
...

J'ai essayé de redémarrer solr dans mon dossier /var/www/sirene_api_production/current mais rien ne change.
Auriez vous une idée ?

Merci d'avance

**Comment by Samuelfaure** [comment]
Bonjourm

Je vous invite à bien regarder le README, section troubleshooting : cette erreur est fréquente quand Mina ne déploie pas les fichiers correctement. Il vous faudra copier manuellement un ou deux fichiers et cela devrait marcher.

**Comment by mpo-deltacode** [comment]
L'erreur venait bien de la limite de mémoire, j'ai retirer la mémoire dans mon fichier et ça à bien lancé le tout après un redémarrage de Solr

Merci a vous
