### ISSUE TITLE
Rechercher des établissement fermés

### ISSUE THREAD

**Issue by vandrieu** [etalab/sirene_as_api#253]
Bonjour,

J'aurais besoin de récupérer des données sur des établissements ayant travaillé avec mon client, pour certains il s'agit de collaborations datant d'il y a 4 ou 5 ans. Parmi ces entreprises, certaines n'existent plus, mais nous avons quand même besoin des données, nous avons donc essayé la recherche par SIRET et SIREN, sans succès.

Exemples,

- Monsieur Verzeni, entreprise cessée à l'INSEE le 06-08-2018, https://entreprise.data.gouv.fr/api/sirene/v1/siret/33079025400032 me renvoie "no result"

- Monsieur Patureau, entreprise cessée à l'INSEE le 28-02-2019, https://entreprise.data.gouv.fr/api/sirene/v1/siret/39050378700066 me renvoie "no result"

- EURL AIP, établissement fermé le 01-03-2018, https://entreprise.data.gouv.fr/api/sirene/v1/siret/51201896100015 me renvoie "no result"

Comment pouvons-nous accéder à ces données ?

Merci d'avance.

**Comment by Haelle** [comment]
Les API v1et v2 ne contiennent pas les entreprises fermées.
Par contre l'API v3 les contient
