### ISSUE TITLE
Régression de la fonctionnalité fulltext après mise à jour de l’API en V3

### ISSUE THREAD

**Issue by Dupont75** [etalab/sirene_as_api#277]
Bonjour,

Dans le cadre d’un développement utilisant l’api sirene, je souhaiterais utiliser les fonctionnalités de la V1 à savoir
-	La recherche FullText
-	Recherche autour d’un point et établissement 

Néanmoins la V1 est d’après votre documentation dépréciée et vous préconisez la version V3 qui ne possède pas ces fonctionnalités.

D’où quelques questions :
1 - Peut-on utiliser la V1 même si c’est déprécié et jusqu’à quand allez-vous supporter cette version V1 ?
     OU 
    Doit-on utiliser la V3 ?
2 - Prévoyez-vous de mettre à niveau la V3 avec les fonctionnalités de la V1, c’est-à-dire entre autres :
-	Recherche FullText
-	Recherche autour d’un point et établissement 

Merci par avance.

**Comment by brindu** [comment]
Bonjour @Dupont75 ! 

Je te l'accorde la situation et la documentation ne sont pas clairs. 

La V1 dépréciée concerne les endpoints établissements et entreprises dont les données sont à présent obsolètes depuis le changement de format et mode de diffusion des données par l'INSEE au printemps 2019. 

Par contre, les endpoints de recherche, bien que toujours en V1 sont à jour de la données d'aujourd'hui. Vous pouvez donc les utilisez et nous allons aligner les versions sur l'ensemble des points d'entré. 

Pour récapituler : 
* aujourd'hui */v1/full_text* est fonctionnel et à jour avec la donnée fraiche du répertoire SIRENE
* prochainement, */v3/full_text* sera mis à disposition par soucis de cohérence avec la documentation qui stipule la dépréciation de la V1, mais fonctionnellement il n'y aura aucune différence. Une redirection automatique de */v1/full_text* vers */v3/full_text* sera mise en place pour une migration sans coût pour les usagers :)

**Comment by remioukrat** [comment]
Bonjour @brindu et @Dupont75,

Comme tu l’as indiqué @brindu la redirection se fera automatiquement du endpoint **/v1/full_text** vers **/v3/full_text** mais qu’en est il du format de la réponse ?
Celui-ci sera t-il le même ?

Au delà de la recherche full_text, la même philosophie sera-t-elle appliquée pour la recherche autour d’un point d’intérêt ?

Merci.

**Comment by Dupont75** [comment]
Bonjour @brindu,

Merci pour ta réponse.
J'aimerais avoir quelques informations supplémentaires et je fais suite au commentaire de @remioukrat

1 - Lorsque le v3/full_text sera disponible avec la redirection automatique, quel sera le format du JSon retourné ?
Le format Full_Text retourne une liste d'établissements, quel format sera retourné : V1 ou V3 ?

2 - Concernant la recherche autour d’un point et établissement disponible en V1, 
- Est-elle fonctionnelle en V1 comme la recherche FullText ?
- Sera-t-elle disponible aussi prochainement en V3 ? et si oui mêmes questions que la 1ere question, quel sera le format retourné V1 ou V3 pour les établissements ?

Merci par avance.

**Comment by brindu** [comment]
> La V1 dépréciée concerne les endpoints établissements et entreprises

Je le répète : la V1 est obsolète pour les endpoints établissements et entreprises **uniquement**, cela est dû à un changement non compatible ascendant dans le processus de diffusion de l'INSEE. Les autres points d'entrés ne sont pas impactés. Cela ferait plus de sens de les versionner indépendamment mais cela induit visiblement trop de confusion. On va donc introduire la V3 pour tout le reste des endpoints, mais c'est uniquement décoratif. 

> prochainement, /v3/full_text sera mis à disposition par soucis de cohérence avec la documentation qui stipule la dépréciation de la V1, mais fonctionnellement il n'y aura aucune différence. Une redirection automatique de /v1/full_text vers /v3/full_text sera mise en place pour une migration sans coût pour les usagers :)

J'ai pris l'exemple de la recherche full text mais il en va de même pour la recherche géographique et je peux difficilement être plus précis : **aucune différence fonctionnelle**, **migration sans coût pour les usagers**. Pour le détail sur le format d'appel et de réponse je vous invite à consulter la documentation et à utiliser l'actuelle V1, il n'y aura aucune différence en V3 à l'exception de l'URL (qui contiendra V3 ou non plus V1...).

Je ferme cette issue qui fait doublon avec #262.
