### ISSUE TITLE
Fichiers stocks indisponibles

### ISSUE THREAD

**Issue by julien1619** [etalab/sirene_as_api#292]
Les fichiers stocks des unités légales et des établissements utilisés pour recharger la base ne sont plus disponibles à l'adresse indiquée : [https://files.data.gouv.fr/insee-sirene/StockUniteLegale_utf8.zip](https://files.data.gouv.fr/insee-sirene/StockUniteLegale_utf8.zip)

Cela fait suite à l'incendie du datacenter d'OVH à Strasbourg, je suppose que cette adresse sera rétablie bientôt, mais dans le doute, je préférais créer le ticket ici.

**Comment by davidbullado** [comment]
Bonjour, c'est juste pour vous signaler que le lien indiqué semble actuellement fonctionner.

**Comment by davidbullado** [comment]
Une question cependant si vous me le permettez, lorsque j'essaie de mettre à jour ma base avec la commande suivante :
`bundle exec rake sirene:update_database`

J'obtiens cette erreur :
```
rake aborted!
NoMethodError: undefined method `captures' for nil:NilClass
```
Savez-vous si cette erreur est liée au problème de l'incendie d'OVH ?

**Comment by julien1619** [comment]
> Bonjour, c'est juste pour vous signaler que le lien indiqué semble actuellement fonctionner.

Ah ! Très juste, ça n'était pas le cas tout à l'heure. Je ferme ce ticket dans ce cas. Concernant l'erreur que vous avez, je ne saurais pas dire. Peut-être créer un ticket séparé ?
