### ISSUE TITLE
Better names for attributes

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/sirene_as_api#33]
The names for the attributes in the SIREN database aren't explicit enough. We need more clarity for our users.

Exemple :
    **type_voie** could be renamed **adresse_type_voie**

**WARNING : Do not push in production before the API entreprise backup using the API is up to date.**
^Also the frontend.

**Comment by giglemad** [comment]
👍

**Comment by Samuelfaure** [comment]
List of attribute names and some suggestions :

Present name | name in INSEE database | **Name propositions**
------------ | ------------- | -------------
    siret siret
    nic |nic|
    siren |siren|
    nic |nic| 
    l1_normalisee |l1_normalisee|
    l2_normalisee |l2_normalisee|
    l3_normalisee |l3_normalisee|
    l4_normalisee |l4_normalisee|
    l5_normalisee |l5_normalisee|
    l6_normalisee |l6_normalisee|
    l7_normalisee |l7_normalisee|
    l1_declaree |l1_declaree|
    l2_declaree |l2_declaree|
    l3_declaree |l3_declaree|
    l4_declaree |l4_declaree|
    l5_declaree |l5_declaree|
    l6_declaree |l6_declaree|
    l7_declaree |l7_declaree|
    numero_voie |numvoie|
    indice_repetition |indrep|
    type_voie |typvoie|
    libelle_voie |libvoie|
    code_postal |codpos|
    cedex |cedex|
    region |rpet|
    libelle_region |libreg|
    departement |depet|
    arrondissement |arronet|
    canton |ctonet|
    commune |comet|
    libelle_commune |libcom|
    departement_unite_urbaine |du|
    taille_unite_urbaine |tu|
    numero_unite_urbaine |uu|
    etablissement_public_cooperation_intercommunale |epci|
    tranche_commune_detaillee |tcd|
    zone_emploi |zemet|
    is_siege |siege|
    enseigne |enseigne|
    indicateur_champ_publipostage |ind_publipo|
    statut_prospection |diffcom|
    date_introduction_base_diffusion |amintret|
    nature_entrepreneur_individuel |natetab|
    libelle_nature_entrepreneur_individuel |libnatetab|
    activite_principale |apet700|
    libelle_activite_principale |libapet|
    date_validite_activite_principale |dapte|
    tranche_effectif_salarie |tefet|
    libelle_tranche_effectif_salarie |libtefet|
    tranche_effectif_salarie_centaine_pret |efetcent|
    date_validite_effectif_salarie |defet|
    origine_creation |origine|
    date_creation |dcret|
    date_debut_activite |ddebact|
    nature_activite |activnat|
    lieu_activite |lieuact|
    type_magasin |actisurf|
    is_saisonnier |saisonat|
    modalite_activite_principale |modet|
    caractere_productif |prodet|
    participation_particuliere_production |prodpart|
    caractere_auxiliaire |auxilt|
    nom_raison_sociale |nomen_long|
    sigle |sigle|
    nom |nom|
    prenom |prenom|
    civilite |civilite|
    numero_rna |rna|
    nic_siege |nicsiege|
    region_siege |rpen|
    departement_commune_siege |depcomen|
    email |adr_mail|
    nature_juridique_entreprise |nj|
    libelle_nature_juridique_entreprise |libnj|
    activite_principale_entreprise |apen700|
    libelle_activite_principale_entreprise |libapen|
    date_validite_activite_principale_entreprise |dapen|
    activite_principale_registre_metier |aprm|
    is_ess |ess|
    date_ess |dateess|
    tranche_effectif_salarie_entreprise |tefen|
    libelle_tranche_effectif_salarie_entreprise |libtefen|
    tranche_effectif_salarie_entreprise_centaine_pret |efencent|
    date_validite_effectif_salarie_entreprise |defen|
    categorie_entreprise |categorie|
    date_creation_entreprise |dcren|
    date_introduction_base_diffusion_entreprise |amintren|
    indice_monoactivite_entreprise |monoact|
    modalite_activite_principale_entreprise |moden|
    caractere_productif_entreprise |proden|
    date_validite_rubrique_niveau_entreprise_esa |esaann|
    tranche_chiffre_affaire_entreprise_esa |tca|
    activite_principale_entreprise_esa |esaapen|
    premiere_activite_secondaire_entreprise_esa |esasec1n|
    deuxieme_activite_secondaire_entreprise_esa |esasec2n|
    troisieme_activite_secondaire_entreprise_esa |esasec3n|
    quatrieme_activite_secondaire_entreprise_esa |esasec4n|
    nature_mise_a_jour |vmaj|
    indicateur_mise_a_jour_1 |vmaj1|
    indicateur_mise_a_jour_2 |vmaj2|
    indicateur_mise_a_jour_3 |vmaj3|
    date_mise_a_jour |datemaj|
    type_evenement |eve|
    date_evenement |dateve|
    type_creation |typcreh|
    date_reactivation_etablissement |dreactet|
    date_reactivation_entreprise |dreacten|
    indicateur_mise_a_jour_enseigne_entreprise |madresse|
    indicateur_mise_a_jour_activite_principale_etablissement |menseigne|
    indicateur_mise_a_jour_adresse_etablissement |mapet|
    indicateur_mise_a_jour_caractere_productif_etablissement |mprodet|
    indicateur_mise_a_jour_caractere_auxiliaire_etablissement |mauxilt|
    indicateur_mise_a_jour_nom_raison_sociale |mnomen|
    indicateur_mise_a_jour_sigle |msigle|
    indicateur_mise_a_jour_nature_juridique |mnj|
    indicateur_mise_a_jour_activite_principale_entreprise |mapen|
    indicateur_mise_a_jour_caractere_productif_entreprise |mproden|
    indicateur_mise_a_jour_nic_siege |mnicsiege|
    siret_predecesseur_successeur |siretps|
    telephone |tel|
    l1_normalisee |l1_normalisee|
    l2_normalisee |l2_normalisee|
    l3_normalisee |l3_normalisee|
    l4_normalisee |l4_normalisee|
    l5_normalisee |l5_normalisee|
    l6_normalisee |l6_normalisee|
    l7_normalisee |l7_normalisee|
    l1_declaree |l1_declaree|
    l2_declaree |l2_declaree|
    l3_declaree |l3_declaree|
    l4_declaree |l4_declaree|
    l5_declaree |l5_declaree|
    l6_declaree |l6_declaree|
    l7_declaree |l7_declaree|
    numero_voie |numvoie|
    indice_repetition |indrep|
    type_voie |typvoie|
    libelle_voie |libvoie|
    code_postal |codpos|
    cedex |cedex|
    region |rpet|
    libelle_region |libreg|
    departement |depet|
    arrondissement |arronet|
    canton |ctonet|
    commune |comet|
    libelle_commune |libcom|
    departement_unite_urbaine |du|
    taille_unite_urbaine |tu|
    numero_unite_urbaine |uu|
    etablissement_public_cooperation_intercommunale |epci|
    tranche_commune_detaillee |tcd|
    zone_emploi |zemet|
    is_siege |siege|
    enseigne |enseigne|
    indicateur_champ_publipostage |ind_publipo|
    statut_prospection |diffcom|
    date_introduction_base_diffusion |amintret|
    nature_entrepreneur_individuel |natetab|
    libelle_nature_entrepreneur_individuel |libnatetab|
    activite_principale |apet700|
    libelle_activite_principale |libapet|
    date_validite_activite_principale |dapte|
    tranche_effectif_salarie |tefet|
    libelle_tranche_effectif_salarie |libtefet|
    tranche_effectif_salarie_centaine_pret |efetcent|
    date_validite_effectif_salarie |defet|
    origine_creation |origine|
    date_creation |dcret|
    date_debut_activite |ddebact|
    nature_activite |activnat|
    lieu_activite |lieuact|
    type_magasin |actisurf|
    is_saisonnier |saisonat|
    modalite_activite_principale |modet|
    caractere_productif |prodet|
    participation_particuliere_production |prodpart|
    caractere_auxiliaire |auxilt|
    nom_raison_sociale |nomen_long|
    sigle |sigle|
    nom |nom|
    prenom |prenom|
    civilite |civilite|
    numero_rna |rna|
    nic_siege |nicsiege|
    region_siege |rpen|
    departement_commune_siege |depcomen|
    email |adr_mail|
    nature_juridique_entreprise |nj|
    libelle_nature_juridique_entreprise |libnj|
    activite_principale_entreprise |apen700|
    libelle_activite_principale_entreprise |libapen|
    date_validite_activite_principale_entreprise |dapen|
    activite_principale_registre_metier |aprm|
    is_ess |ess|
    date_ess |dateess|
    tranche_effectif_salarie_entreprise |tefen|
    libelle_tranche_effectif_salarie_entreprise |libtefen|
    tranche_effectif_salarie_entreprise_centaine_pret |efencent|
    date_validite_effectif_salarie_entreprise |defen|
    categorie_entreprise |categorie|
    date_creation_entreprise |dcren|
    date_introduction_base_diffusion_entreprise |amintren|
    indice_monoactivite_entreprise |monoact|
    modalite_activite_principale_entreprise |moden|
    caractere_productif_entreprise |proden|
    date_validite_rubrique_niveau_entreprise_esa |esaann|
    tranche_chiffre_affaire_entreprise_esa |tca|
    activite_principale_entreprise_esa |esaapen|
    premiere_activite_secondaire_entreprise_esa |esasec1n|
    deuxieme_activite_secondaire_entreprise_esa |esasec2n|
    troisieme_activite_secondaire_entreprise_esa |esasec3n|
    quatrieme_activite_secondaire_entreprise_esa |esasec4n|
    nature_mise_a_jour |vmaj|
    indicateur_mise_a_jour_1 |vmaj1|
    indicateur_mise_a_jour_2 |vmaj2|
    indicateur_mise_a_jour_3 |vmaj3|
    date_mise_a_jour |datemaj|
    type_evenement |eve|
    date_evenement |dateve|
    type_creation |typcreh|
    date_reactivation_etablissement |dreactet|
    date_reactivation_entreprise |dreacten|
    indicateur_mise_a_jour_enseigne_entreprise |madresse|
    indicateur_mise_a_jour_activite_principale_etablissement |menseigne|
    indicateur_mise_a_jour_adresse_etablissement |mapet|
    indicateur_mise_a_jour_caractere_productif_etablissement |mprodet|
    indicateur_mise_a_jour_caractere_auxiliaire_etablissement |mauxilt|
    indicateur_mise_a_jour_nom_raison_sociale |mnomen|
    indicateur_mise_a_jour_sigle |msigle|
    indicateur_mise_a_jour_nature_juridique |mnj|
    indicateur_mise_a_jour_activite_principale_entreprise |mapen|
    indicateur_mise_a_jour_caractere_productif_entreprise |mproden|
    indicateur_mise_a_jour_nic_siege |mnicsiege|
    siret_predecesseur_successeur |siretps|
    telephone |tel|

**Comment by giglemad** [comment]
Ça demande un peu plus d investigations que prévu mais on y reviendra a la fin du mois.
