### ISSUE TITLE
Dockerize deployment ?

### ISSUE THREAD

**Issue by thaichat04** [etalab/sirene_as_api#96]
Super votre projet !!!

Par contre, pour simplifier le déployement, possible de fournir un image docker wrapper l'ensemble ?

**Comment by Samuelfaure** [comment]
Merci à l'intêret que vous portez au projet !

Pour le moment, nous ne prévoyons pas d'intégrer un dockerfile clef-en-main, nous avons des chantiers assez urgents sur le feu, notamment la construction d'une API de qualité similaire pour le fichier RNA (https://github.com/betagouv/rna_as_api)

Un script Ansible (lien dans le README) est à disposition pour un deploiement facile, mais le script a du retard dans la maintenance.

Si je monte en compétence sur Docker je tenterais mais pas avant la fin de l'année. Cela dit, notre license étant MIT, les contributions sont bienvenues ;)

**Comment by Samuelfaure** [comment]
Back to work, this is now priority

**Comment by thaichat04** [comment]
Great news ! nous avons commencé ce travail dockeriser, mais pas terminé: https://github.com/dhatim/sirene_as_api/commits/master

**Comment by Samuelfaure** [comment]
That's awesome :) Je ne suis toujours pas fluent en docker pour le moment, je comptais le devenir. Si vous pensez pouvoir proposer une PR dans les mois à venir c'est top, sinon je tenterais de le faire en copiant votre travail.

**Comment by Samuelfaure** [comment]
@thaichat04 La dockerisation est normalement terminée (cf PR), tout a l'air de fonctionner, j'importe à nouveau les données et je fais un dernier test demain.
